-- Query: SELECT T2.School, T2.DOC FROM frpm AS T1 INNER JOIN schools AS T2 ON T1.CDSCode = T2.CDSCode WHERE T2.FundingType = 'Locally funded' AND (T1.`Enrollment (K-12)` - T1.`Enrollment (Ages 5-17)`) > (SELECT AVG(T3.`Enrollment (K-12)` - T3.`Enrollment (Ages 5-17)`) FROM frpm AS T3 INNER JOIN schools AS T4 ON T3.CDSCode = T4.CDSCode WHERE T4.FundingType = 'Locally funded')
Project($35, $54, id=10)
  Filter(condition=$53 = 'Locally funded' AND $18 - $23 > scalarquery( Aggregate(keys=[], aggs=[AVG($0)])
  Project($18 - $23, id=4)
    Filter(condition=$53 = 'Locally funded', id=3)
      Join(condition=$0 = $29, type=INNER, id=2)
        Scan(table=frpm, id = 0)
        Scan(table=schools, id = 1)), id=9)
    Join(condition=$0 = $29, type=INNER, id=8)
      Scan(table=frpm, id = 6)
      Scan(table=schools, id = 7)