from typing import NewType, TypeVar



UniqueId = NewType("UniqueId", str)
Pattern = NewType('Pattern', str)

CONSTRAINT = 'CONSTRAINT'
REQUIRE = 'REQUIRE'
DATA = 'DATA'
GROUP_KEY = 'GROUP_KEY'
GROUP_DATA = 'GROUP_DATA'
DEFAULT_BRANCH = 'DEFAU0'
DEFAULT_POSITIVE_BRANCH = 'DEFAULT_POSITIVE_BRANCH'
DEFAULT_NEGATIVE_BRANCH = 'DEFAULT_NEGATIVE_BRANCH'

DEFAULT_GROUP_COUNT = 'DEFAULT_GROUP_COUNT'
DEFAULT_GROUP_SIZE = 'DEFAULT_GROUP_SIZE'

